trigger:
  - main

pool:
  vmImage: 'linux-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/Bergmania.OpenStreetMap.csproj'
      includesymbols: true
      versioningScheme: 'off'